' Use this source on this site:
' https://www.planttext.com/
@startuml

Title PUSH operation timing

legend
lower case: UL inputs ( controlled by adapter or mem )
UPPER case: UL outputs ( controlled by UL )
end legend

robust "adapt_push" as AP
robust "adapt_we" as AWE
robust "ADAPT_WE_ACK" as AWEACK
concise "STATE" as ST
robust "MEM_WE" as MWE
robust "mem_we_ack" as MWEACK

scale 100 as 150 pixels


@0
AWE is L
AWEACK is L
AP is L
ST is idle
MWE is L
MWEACK is L

@1
AWEACK is H
MWEACK is H

@30
AWE is H

@50
AP is H
AP -> ST@+50 : Push operation initiated

@100
ST is push_calc_addr
AWEACK is L
ST -> AWEACK
AWEACK -> AWE@+20 
AWEACK -> AP@+20 

@120
AWE is L
AP is L

@200
MWE is H
ST is push_before_mem
ST -> MWE

@220
MWEACK is L
MWEACK -> ST@+80

@300
ST is push_after_mem
MWE is L
ST -> MWE

@380
MWEACK is H
MWEACK -> ST@+20

@400
ST is idle
AWEACK is H
ST -> AWEACK


@MWE
@200 <-> @380 : < UL wait for MEM >

@AP
@50 <-> @400 : < Adapt wait for UL >


@enduml